version: "3.9"

services:
  mysql:
    image: mysql:latest                
    container_name: mysql_container
    networks:
      - db_network
    volumes:
      - db_volume:/var/lib/mysql
      - ./mysql/conf/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    expose:
      - "3306"                          
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app_container
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - db_network
      - site_network
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=testdb
    expose:
      - "4743"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4743/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "5423:824"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - site_network
    depends_on:
      app:
        condition: service_healthy

networks:
  db_network:
  site_network:

volumes:
  db_volume: